### ISSUE TITLE
Deploying an extension built with create-react-app

### ISSUE THREAD

**Issue by stk26kakarla** [Adobe-Marketing-Cloud-Activation/extension-facebookpixel#6]
I am building an extension in React using create-react-app scaffolding tool (using React for the first time). I haven't added any functionality for it to be an Adobe Launch extension.
I am unable to understand the following and expecting some help, please!!

1. What basis should I create an extension.json file, what would be the view path? How can I determine, by index.html file in public folder or by the index.js file in the src folder? You mentioned base  path as "dist/", where is it? 
2. How to package it as .zip file for Launch Extension uploader? Do I have to simply eject and zip it or do I have to build it and zip it? If to eject and zip, what about node_modules with all unnecessary libraries that downloaded during create-react-app? npm run build doesn't copy extension.json to the build folder, how will it deploy as an extension in Adobe Launch?

**Comment by Aaronius** [comment]
Good questions. Your `viewBasePath` in extension.json should be set to `build/`, since that is where your built view files are placed by create-react-app after running `npm run build`. The value of your `viewPath` will then be relative to the `build` directory.  For example, if you were building an action and the HTML file you would like displayed inside the Launch UI is `build/index.html`, your `extension.json` would look something like this:

```
...
"viewBasePath": "build/",
"actions": [
    {
      "name": "send-beacon",
      "displayName": "Send Beacon",
      "libPath": "src/lib/actions/sendBeacon.js",
      "viewPath": "index.html",
      "schema":  {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type": "object",
        "properties": { }
      }
    }
  ]
...
```

For packaging, I would recommend using the https://www.npmjs.com/package/@adobe/reactor-packager tool. It will read your extension.json file and determine which files need to be included into the zip file. For example, if it sees that the `viewBasePath` is set to `build/`, then it will include all the files from `build/` into the zip file it creates. You'll need to run `npm run build` to build your view files before running the packager. You shouldn't have to eject. The packager tool will exclude `node_modules`.

Just so you're aware, we have a dedicated Slack workspace for questions like these if you'd like to join. We'll be able to help you out better there. You can sign up here: http://join.launchdevelopers.chat/
